describe('Proyecto veterinaria - Mascota', () => {
  beforeEach("Visitar Login Usuario Default", () => {
    cy.session("Login", () => {
      cy.visit(Cypress.env('base_url'))
      cy.get("[name='username']")
        .type("administrador@hotmail.com")
      cy.get("[name='password']")
        .type("123")
      cy.get("[type='submit']").click()
    })
  })
  it('Registrar Mascota', () => {
    cy.visit(Cypress.env('base_url2'))
    cy.get('#agMasc').click()
    cy.location('pathname').should('eq','/gestionMascota')
    cy.get('#btnRegMascota').click()
    cy.location('pathname').should('eq','/formularioMascota')
    cy.get('#nombre').type('Firulais')
    cy.get('#edad').type('9')
    cy.get('#Sexo').select('M')
    cy.get('#especie').select('Perro')
    cy.get('#raza').type('Pitbull')
    cy.get('#estatura').clear()
    cy.get('#estatura').type('50')
    cy.get('#peso').clear()
    cy.get('#peso').type('35')
    cy.get('#color').clear()
    cy.get('#color').type('negro')
    cy.get("[name=\'propietario\']").select('1').invoke('val').then((value)=>{
      cy.log('selected value -'+value)
    })
    cy.get('#btn-registrar').click()
    cy.location('pathname').should('eq','/gestionMascota')    
  })
  it('Editar Mascota', () => {
    cy.visit(Cypress.env('base_url2'))
    cy.get('#agMasc').click()
    cy.location('pathname').should('eq','/gestionMascota')
    cy.get('#editMascota').click()
    cy.location('pathname').should('eq','/formularioMascota/1')  
    cy.get('#nombre').clear()
    cy.get('#nombre').type('Mini Mini')
    cy.get('#edad').clear()
    cy.get('#edad').type('8')
    cy.get('#Sexo').select('M')
    cy.get('#especie').select('Perro')
    cy.get('#raza').clear()
    cy.get('#raza').type('Chusco')
    cy.get('#estatura').clear()
    cy.get('#estatura').type('30')
    cy.get('#peso').clear()
    cy.get('#peso').type('16')
    cy.get('#color').clear()
    cy.get('#color').type('Blanco')
    cy.get("[name=\'propietario\']").select('1').invoke('val').then((value)=>{
      cy.log('selected value -'+value)
    })
    cy.get('#btn-registrar').click()
    cy.location('pathname').should('eq','/gestionMascota')     
  })
  it('Ver Mascota', () => {
    cy.visit(Cypress.env('base_url4'))
    cy.get('#btn-ver').click()
    cy.location('pathname').should('eq','/detalleMascota/1')
    cy.get('#btn-regresar').click()
    cy.location('pathname').should('eq','/gestionMascota')  
  })
  it('Ver Historial Medico', () => {
    cy.visit(Cypress.env('base_url4'))
    cy.get('#btn-hisMed').click()
    cy.location('pathname').should('eq','/historialMedico/1')
    cy.get('#btn-regresar').click()
    cy.location('pathname').should('eq','/gestionMascota')  
  })
  /*
  it('Eliminar Mascota', () => { 
    cy.visit(Cypress.env('base_url4'))
    cy.get('#btn-eliminar-mascota').click({force:true})
    cy.get('.swal2-confirm').click({force:true})
    cy.get('.swal2-confirm').click({force:true})
  })
  */
  it('Cerrar Sesion Usuario Default', () => {
    
    cy.visit(Cypress.env('base_url6'))
    cy.get('#logout') .click()
    cy.location('pathname').should('eq','/login')
  })
})