describe('Proyecto veterinaria', () => {
  beforeEach("Visitar Login Usuario Default", () => {
    cy.session("Login", () => {
      cy.visit(Cypress.env('base_url'))
      cy.get("[name='username']")
        .type("administrador@hotmail.com")
      cy.get("[name='password']")
        .type("123")
      cy.get("[type='submit']").click()
    })
  })
  it('Entrar al Gestionar Rol', () => {
    cy.visit(Cypress.env('base_url2'))
    cy.get('#btnRegRol').click({force:true})
    cy.location('pathname').should('eq', '/GestionRol')
  })
  it('Registrar Rol Cajero', () => {
      
    cy.visit(Cypress.env('base_url3'))
    cy.get('#btnRegistrarRoles').click({force:true})
    cy.location('pathname').should('eq','/formularioRol')
    cy.get('#nombre').type('Cajero')
    .should('have.value','Cajero');
    cy.get('#btn-registrar').click({force:true})
    cy.location('pathname').should('eq','/GestionRol')  
  })
  it('Modificar Rol Cajero', () => {
      
    cy.visit(Cypress.env('base_url3'))
    cy.get('#btn-editar-rol').click()
    cy.location('pathname').should('contain','/formularioRol/')
    cy.get('#nombre').clear().type('Medico')
    .should('have.value','Medico');
    cy.get('#btn-registrar').click()
    cy.location('pathname').should('eq','/GestionRol')  
  })
  it('Registrar Empleado', () => {
      
    cy.visit(Cypress.env('base_url2'))
    cy.get('#btnRegEmpleado').click()
    cy.location('pathname').should('eq','/formularioEmpleado')
    cy.get('#dni').type('73189018')
    cy.get('#nombre').type('Adriana')
    cy.get('#apellido').type('Valverde')
    cy.get('#direccion').type('Av. Los Jardines 123')
    cy.get('#email').type('adriana17@gmail.com')
    cy.get('#celular').type('987654321')
    cy.get('#sexo').select('M')
    cy.get('#fecha_Nacimiento').type('2002-04-12')
    cy.get('#usuario').type('Adri17')
    cy.get('#password').type('123')
    cy.get("[name=\'tipo_rol\']").select('2').invoke('val').then((value)=>{
      cy.log('selected value -'+value)
    })
    cy.get('#btn-registrar').click()
  })
  it('Editar Empleado', () => {
    cy.visit(Cypress.env('base_url2'))
    cy.get('#btnEditar').click()
    cy.location('pathname').should('eq','/formularioEmpleado/1')
    cy.get('#dni').clear()
    cy.get('#dni').type('73189018')
    cy.get('#nombre').clear()
    cy.get('#nombre').type('Adriana')
    cy.get('#apellido').clear()
    cy.get('#apellido').type('Valverde')
    cy.get('#direccion').clear()
    cy.get('#direccion').type('Av. Los Jardines 123')
    cy.get('#email').clear()
    cy.get('#email').type('adriana17@gmail.com')
    cy.get('#celular').clear()
    cy.get('#celular').type('987654321')
    cy.get('#sexo').select('F')
    cy.get('#fecha_Nacimiento').type('2002-04-12')
    cy.get('#usuario').clear()
    cy.get('#usuario').type('Adri17')
    cy.get('#password').clear()
    cy.get('#password').type('123')
    cy.get("[name=\'tipo_rol\']").select('2').invoke('val').then((value)=>{
      cy.log('selected value -'+value)
    })
    cy.get('#btn-registrar').click()
  })
  it('Ver Empleado', () => {
    cy.visit(Cypress.env('base_url2'))
    cy.get('#btn-ver').click()
    cy.location('pathname').should('eq','/detalleEmpleado/1')
    cy.get('#btn-regresar').click()
    cy.location('pathname').should('eq','/gestionAdmin')  
  })
  
  it('Registrar Propietario', () => {
    cy.visit(Cypress.env('base_url2'))
    cy.get('#agProp').click()
    cy.location('pathname').should('eq','/gestionPropietario')
    cy.get('#btnRegPropietario').click()
    cy.location('pathname').should('eq','/formularioPropietario')
    cy.get('#nomPropietario').type('Rodrigo Jorge Alonso Gomez Velasquez')
    cy.get('#direccion').type('Av Villa Maria del Triunfo')
    cy.get('#correo').type('rodrigoval@gmail.com')
    cy.get('#celPropietario').type('954254114')
    cy.get('#btn-Propietario').click()   
  })
  it('Editar Propietario', () => {
    cy.visit(Cypress.env('base_url2'))
    cy.get('#agProp').click()
    cy.location('pathname').should('eq','/gestionPropietario')
    cy.get('#editProp').click()
    cy.location('pathname').should('eq','/formularioPropietario/1')
    cy.get('#nomPropietario').clear()
    cy.get('#nomPropietario').type('Alvaro Gongora Renteria')
    cy.get('#direccion').clear()
    cy.get('#direccion').type('Av Manzanales')
    cy.get('#correo').clear()
    cy.get('#correo').type('alvarogongora@gmail.com')
    cy.get('#celPropietario').clear()
    cy.get('#celPropietario').type('999999991')
    cy.get('#btn-Propietario').click()  
  })
  it('Registrar Mascota', () => {
    cy.visit(Cypress.env('base_url2'))
    cy.get('#agMasc').click()
    cy.location('pathname').should('eq','/gestionMascota')
    cy.get('#btnRegMascota').click()
    cy.location('pathname').should('eq','/formularioMascota')
    cy.get('#nombre').type('Firulais')
    cy.get('#edad').type('9')
    cy.get('#Sexo').select('M')
    cy.get('#especie').select('Perro')
    cy.get('#raza').type('Pitbull')
    cy.get('#estatura').clear()
    cy.get('#estatura').type('50')
    cy.get('#peso').clear()
    cy.get('#peso').type('35')
    cy.get('#color').clear()
    cy.get('#color').type('negro')
    cy.get("[name=\'propietario\']").select('1').invoke('val').then((value)=>{
      cy.log('selected value -'+value)
    })
    cy.get('#btn-registrar').click()
    cy.location('pathname').should('eq','/gestionMascota')    
  })
  it('Editar Mascota', () => {
    cy.visit(Cypress.env('base_url2'))
    cy.get('#agMasc').click()
    cy.location('pathname').should('eq','/gestionMascota')
    cy.get('#editMascota').click()
    cy.location('pathname').should('eq','/formularioMascota/1')  
    cy.get('#nombre').clear()
    cy.get('#nombre').type('Mini Mini')
    cy.get('#edad').clear()
    cy.get('#edad').type('8')
    cy.get('#Sexo').select('M')
    cy.get('#especie').select('Perro')
    cy.get('#raza').clear()
    cy.get('#raza').type('Chusco')
    cy.get('#estatura').clear()
    cy.get('#estatura').type('30')
    cy.get('#peso').clear()
    cy.get('#peso').type('16')
    cy.get('#color').clear()
    cy.get('#color').type('Blanco')
    cy.get("[name=\'propietario\']").select('1').invoke('val').then((value)=>{
      cy.log('selected value -'+value)
    })
    cy.get('#btn-registrar').click()
    cy.location('pathname').should('eq','/gestionMascota')     
  })
  it('Ver Mascota', () => {
    cy.visit(Cypress.env('base_url4'))
    cy.get('#btn-ver').click()
    cy.location('pathname').should('eq','/detalleMascota/1')
    cy.get('#btn-regresar').click()
    cy.location('pathname').should('eq','/gestionMascota')  
  })
  
  it('Registrar Servicio', () => {
    cy.visit(Cypress.env('base_url2'))
    cy.get('#Servicios').click()
    cy.location('pathname').should('eq','/menu-servicio')
    cy.get('#btnGestionarServicio').click()
    cy.location('pathname').should('eq','/gestionServicio')
    cy.get('#btnRegistrarServicio').click()
    cy.location('pathname').should('eq','/formularioServicio')
    cy.get('#descripcion').type('Baño')
    cy.get('#precio').clear()
    cy.get('#precio').type('30')
    cy.get('#tipo_mascota').select('Perro')
    cy.get('#btn-registrar').click()
    cy.location('pathname').should('eq','/gestionServicio')  
  })
  it('Editar Servicio', () => {
    cy.visit(Cypress.env('base_url2'))
    cy.get('#Servicios').click()
    cy.location('pathname').should('eq','/menu-servicio')
    cy.get('#btnGestionarServicio').click()
    cy.location('pathname').should('eq','/gestionServicio')
    cy.get('#editarServ').click()
    cy.location('pathname').should('eq','/formularioServicio/1')
    cy.get('#descripcion').clear()
    cy.get('#descripcion').type('Baño')
    cy.get('#precio').clear()
    cy.get('#precio').type('20')
    cy.get('#btn-registrar').click()
    cy.location('pathname').should('eq','/gestionServicio')  
  })
  it('Ingresar Catalogo Servicio', () => {
    cy.visit(Cypress.env('base_url2'))
    cy.get('#Servicios').click()
    cy.location('pathname').should('eq','/menu-servicio')
    cy.get('#btnCatalogoServicio').click()
    cy.location('pathname').should('eq','/catalogoServicios')
    cy.get('#btnRegresar').click()
  })
  
  it('Registrar Cita', () => {
    cy.visit(Cypress.env('base_url2'))
    cy.get('#Citas').click()
    cy.location('pathname').should('eq','/gestionCitas')
    cy.get('#btnRegistrarCita').click()
    cy.location('pathname').should('eq','/formularioCitas')
    cy.get("[name=\'empleado\']").select('1').invoke('val').then((value)=>{
      cy.log('selected value -'+value)
    })
    cy.get("[name=\'propietario\']").select('1').invoke('val').then((value)=>{
      cy.log('selected value -'+value)
    })
    cy.get("[name=\'mascota\']").select('1').invoke('val').then((value)=>{
      cy.log('selected value -'+value)
    })
    cy.get("[name=\'servicio\']").select('1').invoke('val').then((value)=>{
      cy.log('selected value -'+value)
    })
    cy.get('#fecha_cita').type('2022-10-19')
    cy.get('#hora_cita').select('8: 00 - 9: 00 a.m.')   
    cy.get('#btn-registrar').click()
    cy.location('pathname').should('eq','/gestionCitas')  
  })
  it('Editar Cita', () => {
    cy.visit(Cypress.env('base_url2'))
    cy.get('#Citas').click()
    cy.location('pathname').should('eq','/gestionCitas')
    cy.get('#btneditarCita').click()
    cy.location('pathname').should('eq','/formularioCitas/1')
    cy.get("[name=\'empleado\']").select('1').invoke('val').then((value)=>{
      cy.log('selected value -'+value)
    })
    cy.get("[name=\'propietario\']").select('1').invoke('val').then((value)=>{
      cy.log('selected value -'+value)
    })
    cy.get("[name=\'mascota\']").select('1').invoke('val').then((value)=>{
      cy.log('selected value -'+value)
    })
    cy.get("[name=\'servicio\']").select('1').invoke('val').then((value)=>{
      cy.log('selected value -'+value)
    })
    cy.get('#fecha_cita').clear() 
    cy.get('#fecha_cita').type('2022-10-20')
    cy.get('#hora_cita').select('10: 00 - 11: 00 a.m.')  
    cy.get('#observaciones').type('La mascota se encuentra bien')

    cy.get('#btn-registrar').click()
    cy.location('pathname').should('eq','/gestionCitas')  
  })
  
  it('Registrar Categoria', () => {
    cy.visit(Cypress.env('base_url2'))
    cy.get('#productos').click()
    cy.location('pathname').should('eq','/menu-producto')
    cy.get('#btnGestionarProducto').click()
    cy.location('pathname').should('eq','/gestionProducto')
    cy.get('#btnCategoria').click()
    cy.location('pathname').should('eq','/GestionCategoria')
    cy.get('#registrarCategoria').click()
    cy.location('pathname').should('eq','/formularioCategoria')
    cy.get('#nombre').type('Ropa')
    cy.get('#btn-registrar').click()
    cy.location('pathname').should('eq','/GestionCategoria')  
  })
  it('Editar Categoria', () => {
    cy.visit(Cypress.env('base_url5'))
    cy.get('#btnEditarCategoria').click()
    cy.location('pathname').should('eq','/formularioCategoria/1')
    cy.get('#nombre').clear()
    cy.get('#nombre').type('Comida')    
    cy.get('#btn-registrar').click()
    cy.location('pathname').should('eq','/GestionCategoria')  
  })
  it('Registrar Producto', () => {
    cy.visit(Cypress.env('base_url2'))
    cy.get('#productos').click()
    cy.location('pathname').should('eq','/menu-producto')
    cy.get('#btnGestionarProducto').click()
    cy.location('pathname').should('eq','/gestionProducto')
    cy.get('#btnRegistrarProducto').click()
    cy.get('#codigo').type('P001')
    cy.get('#nombre').type('Galleta de Perro')
    cy.get('#descripcion').type('Alimenta a tu mascota con las mejores galletas!')
    cy.get('#nombre_Proveedor').type('RicoCan')
    cy.get('#ruc').type('98218759201')
    cy.get('#marca').type('RicoCan')
    cy.get('#precio').clear()
    cy.get('#precio').type('25')
    cy.get('#fecha_Vencimiento').type('2022-12-03')
    cy.get('#stock').type('25')
    cy.get("[name=\'categoria\']").select('1').invoke('val').then((value)=>{
      cy.log('selected value -'+value)
    })
    cy.get('#btn-registrar').click()
    cy.location('pathname').should('eq','/gestionProducto')  
  })
  it('Editar Producto', () => {
    cy.visit(Cypress.env('base_url6'))
    cy.get('#btnEditarProducto').click()
    cy.location('pathname').should('eq','/formularioProducto/1')
    cy.get('#codigo').clear()
    cy.get('#codigo').type('P001')
    cy.get('#nombre').clear()
    cy.get('#nombre').type('Comida para perro')
    cy.get('#descripcion').clear()
    cy.get('#descripcion').type('Alimenta a tu mascota con las mejor comida!')
    cy.get('#nombre_Proveedor').clear()
    cy.get('#nombre_Proveedor').type('DogShow')
    cy.get('#ruc').clear()
    cy.get('#ruc').type('98218759201')
    cy.get('#marca').clear()
    cy.get('#marca').type('DogShow')
    cy.get('#precio').clear()
    cy.get('#precio').type('25')
    cy.get('#fecha_Vencimiento').type('2022-12-03')
    cy.get('#stock').clear()
    cy.get('#stock').type('25')
    cy.get("[name=\'categoria\']").select('1').invoke('val').then((value)=>{
      cy.log('selected value -'+value)
    })
    cy.get('#btn-registrar').click()
    cy.location('pathname').should('eq','/gestionProducto')  
  })
  /*it('Eliminar Producto', () => { 
    cy.visit(Cypress.env('base_url6'))
    cy.get('#btn-eliminar-producto').click({force:true})
    cy.get('.swal2-confirm').click({force:true})
    cy.get('.swal2-confirm').click({force:true})
  })
  it('Eliminar Categoria', () => { 
    cy.visit(Cypress.env('base_url5'))
    cy.get('#btn-eliminar-categoria').click({force:true})
    cy.get('.swal2-confirm').click({force:true})
    cy.get('.swal2-confirm').click({force:true})
  })
  it('Eliminar Cita', () => { 
    cy.visit(Cypress.env('base_url7'))
    cy.get('#btn-eliminar-cita').click({force:true})
    cy.get('.swal2-confirm').click({force:true})
    cy.get('.swal2-confirm').click({force:true})
  })
  it('Eliminar Servicio', () => { 
    cy.visit(Cypress.env('base_url8'))
    cy.get('#btn-eliminar-servicio').click({force:true})
    cy.get('.swal2-confirm').click({force:true})
    cy.get('.swal2-confirm').click({force:true})
  })
  it('Eliminar Mascota', () => { 
    cy.visit(Cypress.env('base_url4'))
    cy.get('#btn-eliminar-mascota').click({force:true})
    cy.get('.swal2-confirm').click({force:true})
    cy.get('.swal2-confirm').click({force:true})
  })
  it('Eliminar Propietario', () => { 
    cy.visit(Cypress.env('base_url9'))
    cy.get('#btn-eliminar-propietario').click({force:true})
    cy.get('.swal2-confirm').click({force:true})
    cy.get('.swal2-confirm').click({force:true})
  })
  it('Eliminar Empleado', () => { 
    cy.visit(Cypress.env('base_url2'))
    cy.get('#btn-eliminar-empleado').click({force:true})
    cy.get('.swal2-confirm').click({force:true})
    cy.get('.swal2-confirm').click({force:true})
  })
  it('Eliminar Rol Cajero', () => { 
    cy.visit(Cypress.env('base_url3'))
    cy.get('#btn-eliminar-rol').click({force:true})
    cy.get('.swal2-confirm').click({force:true})
    cy.get('.swal2-confirm').click({force:true})
  })
  it('Cerrar Sesion Usuario Default', () => {
    
    cy.visit(Cypress.env('base_url6'))
    cy.get('#logout') .click()
    cy.location('pathname').should('eq','/login')
  })*/
})
